### ISSUE TITLE
Unable to correctly package the app

### ISSUE THREAD

**Issue by Osolemio44** [Osolemio44/Appiculture#2]
I moved from a regular javaFX desktop project to a Maven project. A lot of stuffs have changed. I am trying to package the app and run it. No matter how if i package it manually or use maven package. I always get errors. 
Some times, maven cant find javaFX dependency when compiling.
Some times i am able to compile, but maven dont find the manifest.xml
etc... 
I got a lot of errors no matter what i try.

**Comment by albfan** [comment]
A descriptive error would be just run mvn clean install:

```
$ mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------< com.base:Appiculture >------------------------
[INFO] Building Appiculture 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.442 s
[INFO] Finished at: 2021-06-20T09:32:12+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Appiculture: Could not resolve dependencies for project com.base:Appiculture:jar:0.0.1: Failed to collect dependencies at net.sf.jasperreports:jasperreports:jar:6.16.0 -> com.lowagie:itext:jar:2.1.7.js8: Failed to read artifact descriptor for com.lowagie:itext:jar:2.1.7.js8: Could not transfer artifact com.lowagie:itext:pom:2.1.7.js8 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [jaspersoft-third-party (http://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/, default, releases+snapshots), jr-ce-releases (http://jaspersoft.jfrog.io/jaspersoft/jr-ce-releases, default, releases+snapshots)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

jasperreports is always a pain in the ass. Looking at release dates

https://mvnrepository.com/artifact/net.sf.jasperreports/jasperreports

jasperreports 6.16.0 is from a year ago, so upgrading to 6.17.0 (minor version) should be compatible.

For me it resolves it.

**Comment by Osolemio44** [comment]
i just updated to jasperreport 6.17 but i got  the following error when i run mvn install
![image](https://user-images.githubusercontent.com/55595063/122669094-f980f600-d1bb-11eb-8af8-c4286baa6407.png)
The strange thing is sometimes, when i do mvn clean or project> rebuild, the problem disapear temporaly. But then, after few package operation, i got the same error.

**Comment by albfan** [comment]
At least for build modules your need maven compiler plugin 3.7

I pushed changes on #3 and added a CI (continuous integration) so you can be agnostic about building too https://www.travis-ci.com/github/albfan/Appiculture/branches

Just activate travis ci for this repo and file `.travis.yml` will define your build and test suite
